export const RANDOM_MESSAGES = [
  // Encouragement (sarcastic)
  "Nice… I guess.",
  "You did it! Sort of.",
  "Congratulations on your achievement.",
  "Well done, champion.",
  "Outstanding effort there.",
  "You're really going places.",
  "Keep up the good work, I suppose.",
  "That was... something.",
  
  // Sarcasm
  "You've done nothing. Keep going.",
  "Wow, such productivity.",
  "This is what peak performance looks like.",
  "Revolutionary button pressing technique.",
  "You're really changing the world here.",
  "I'm impressed by your dedication to nothing.",
  "Another tap, another step towards... what exactly?",
  "You've mastered the art of pointless interaction.",
  
  // Existential
  "Are you proud of this moment?",
  "What does this say about humanity?",
  "Is this what your ancestors dreamed of?",
  "Time you'll never get back.",
  "Somewhere, a philosopher is crying.",
  "The universe notices your effort (it doesn't).",
  "You exist, therefore you tap.",
  "In the grand scheme of things, this matters not at all.",
  
  // Fake achievements
  "Level 6 Unlocked – Master of Taps.",
  "Achievement: Professional Time Waster",
  "New Skill: Advanced Finger Movement",
  "Rank Up: Certified Button Presser",
  "Badge Earned: Dedication to Nothingness",
  "Title Acquired: Lord/Lady of Pointless Actions",
  "Milestone Reached: 1000 Ways to Waste Time",
  "Trophy Unlocked: Champion of Futility",
  
  // Random/Absurd
  "The button appreciates your attention.",
  "Somewhere, a digital sheep is counting you.",
  "You've contributed to the heat death of the universe.",
  "Error 404: Meaning not found.",
  "Beep boop, human detected.",
  "The algorithm is pleased.",
  "Your finger has excellent taste.",
  "This message was generated by pure chaos.",
  "Fun fact: This isn't fun and it's barely a fact.",
  "You could be doing literally anything else right now.",
];

export const MILESTONE_MESSAGES = {
  10: "10 taps! You're getting warmer... warmer to what, we'll never know.",
  25: "25 taps! Quarter century of achievements right here.",
  50: "50 taps! Halfway to 100! Which is halfway to nothing meaningful.",
  100: "100 taps! Triple digits! Your dedication to futility is inspiring.",
  250: "250 taps! The button is starting to develop feelings for you.",
  500: "500 taps! This is either impressive or deeply concerning.",
  1000: "1000 taps! You've transcended human logic. The button trembles before you.",
};